name: flutter_application_1
description: "A new Flutter project."

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs to work.
dependencies:
  flutter:
    sdk: flutter

  # Add the Cupertino Icons font for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  auto_animated: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0

flutter:
  # Ensure that the Material Icons font is included with your application.
  uses-material-design: true

  # Add assets to your application.
  assets:
    - assets/animation/empty.json # Ensure this path is correct
    - assets/animation/delete.json

  # Uncomment and edit the section below if you want to add custom fonts.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
